<?php
defined('BASEPATH') OR exit('No direct script access allowed');
?>
          <br><br><br>

          <div class="inner cover">
            <p class="lead">
              <p>Lenapo Solutions LLC DBA Encrypt My Wallet wants to remind you, that using our service is free to encrypt and decrypt your password. However we recommend you make a backup of our source code so if we are ever not available and you cannot decrypt your key. Also we recommend you keep your encrypted keys away from the public eye. The code is publicly available online. It is possible for somebody to brute force your password especially with a very poorly chosen password. Your security, your funds, your wallet data, your password, is all YOUR responsibility. If you lose anything you enter in on this website. We cannot get it back. We do not save anything that goes into the encryption or decryption page. We are not responsible for hackers, your personal security, or the way you connect to our website. Always verify what website you are on, never trust third party links. We take 0 responsibility for everything that is done on our website or affiliated with our website. Again, your security is YOUR responsibility. We do not gaurantee anything. Using our site is solely up to you, you release all your rights to hold Lenapo Solutions LLC DBA Encrypt My Wallet accountable for any reason. We reserve the right to refuse service to anybody.</p>
              <br><br><br>
              <b>Always backup your keys:</b> EncryptMyWallet.com does not store your private key, your password for your encrypted private key, or your encrypted wallet key. We make it safer to carry your private key by creating creating a password for you to access your private key. We are not responsible for you losing any information you enter or obtained from our website. We do not save any information of yours during the encrypt or decrypt process. We do not have access to your funds. We cannot recover your password or keys. You are completely responsible for your funds, keys, passwords, and data. 
              <br><br>
              <b>We are not responsible for any loss:</b> EncryptMyWallet, Lenapo Solutions, GitHub, and some of the underlying Javascript libraries we use are under active development. We are not responsible for the safety of your keys (private key, password, or encrypted key). We do not gaurantee that your encrypted key is safe. We advise you not publicly give out your encrypted key as you are the one responsible for your funds. We cannot recover forgotten encrypted keys, passwords, or private keys you encrypted. In the event of site downtime we are not responsible for any loss occured. Using our website you are completely liable for any and all things done on our website. You may choose not to use our service. We recommend you download a copy of our repository for backup safe keeping in the event our website is down you may be able to decrypt or encrypt keys in the future.
              <br><br>
              <b>Translations of EncryptMyWallet:</b> the English version of our website is the official text.
            </p> 
            <p class="lead">
              EncryptMyWallet is committed to ensuring that your privacy is protected. Should we ask you to provide certain information by which you can be identified when using this website, then you can be assured that it will only be used in accordance with this privacy statement. EncryptMyWallet may change this policy from time to time by updating this page. You should check this page from time to time to ensure that you are happy with any changes.
              <br><br>
              Links to other websites
              <br><br>
              Our website may contain links to other websites of interest. However, once you have used these links to leave our site, you should note that we do not have any control over that other website. Therefore, we cannot be responsible for the protection and privacy of any information which you provide whilst visiting such sites and such sites are not governed by this private statement. You should exercise caution and look at the private statement applicable to the website in question.
              <br><br>
              Encrypting & Decrypting
              <br><br>
              Our encryption and decryption algorithims do not save your private keys, your passwords, or your encrypted keys. We do not have access to your funds. We can not properly identify you when using our service. We are not responsible for loss or reverse engineering of your keys or passwords. We do not collect information about your keys, your passwords, or your encrypted keys in any way while using the encrypt or decrypt pages. We do not gaurantee your key can't be reverse engineered or converted into plaintext with or without your password. Using our encryption and decryption process is completely free and we take no responsibility for you using our service now, in the future, or being without our service. In no event shall you hold Lenapo Solutions LLC DBA Encrypt My Wallet, management, employees, third party contributors, respective officers, directors, agents, joint venturers, or representatives accountable for any and all loss by your person or business that used our service or website.
              <br><br>
              Release of Lenapo Solutions LLC DBA Encrypt My Wallet; Indemnification. If you have a dispute with one or more users of the Lenapo Solutions LLC DBA Encrypt My Wallet services, you release Lenapo Solutions LLC DBA Encrypt My Wallet, its affiliates and service providers, and each of their respective officers, directors, agents, joint venturers, employees and representatives from any and all claims, demands and damages (actual and consequential) of every kind and nature arising out of or in any way connected with such disputes. You agree to indemnify and hold Lenapo Solutions LLC DBA Encrypt My Wallet, its affiliates and Service Providers, and each of its or their respective officers, directors, agents, joint venturers, employees and representatives, harmless from any claim or demand (including attorneys' fees and any fines, fees or penalties imposed by any regulatory authority) arising out of or related to your breach of this Agreement or your violation of any law, rule or regulation, or the rights of any third party.
              <br><br>
              <b>We are not responsible for your security.</b>
            </p>
          </div>